name: Start JEST test
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  unit-test-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: JEST test
        run: npm run test
